
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow
    username: root
    password: Raju@123

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8040

server:
  port: 8050
