
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow
    username: root
    password: Raju@123

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/template/mail/

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8040

server:
  port: 8050
